### ISSUE TITLE
Not able to build the apps

### ISSUE THREAD

**Issue by barshuker** [jovanbulck/sgx-step#11]
Hey, i'm currently trying to build the 'foreshadow' app but when i run the makefile i get this error:

[===] Enclave [===]
[GEN] sgx_edger8r encl.edl
make[1]: sgx_edger8r: Command not found
Makefile:84: recipe for target 'edger' failed
make[1]: *** [edger] Error 127
Makefile:72: recipe for target 'build-Enclave' failed
make: *** [build-Enclave] Error 2

I edited the makefile inside the 'Enclave' folder by:
- adding the line:
 SGX_SDK ?= /opt/intel/sgxsdk 
(when i tried to print the value of SGX_SDK through "echo" i got blank output).

- changing the EDGER variable to be 
EDGER		  = $(SGX_SDK)/bin/x64/sgx_edger8r

the error above seemed to be solved but then i encountered a new one:
 [===] Enclave [===]
[GEN] /opt/intel/sgxsdk/bin/x64/sgx_edger8r encl.edl
[CC]  encl_t.c (trusted edge)
[CC]  encl.c (core)
[LD]   encl.o encl_t.o -lsgx_trts encl.unsigned.so
Makefile:51: recipe for target 'encl.so' failed
make[1]: *** [encl.so] Error 127
Makefile:72: recipe for target 'build-Enclave' failed
make: *** [build-Enclave] Error 2

i followed the installation instructions inside the README, would appreciate some help.

Thanks,
Bar.

**Comment by barshuker** [comment]
Solved. turns out i didn't set the environment correctly.
although, i run into a different problem when using 'make run' in the 'foreshadow' folder:

 [===] Enclave [===]
[RM] encl.o encl.unsigned.so encl.so libencl_proxy.a
[RM] encl_t.o encl_u.o encl_t.h encl_t.c encl_u.h encl_u.c
[===] ../../libsgxstep [===]
[RM] apic.o cpu.o debug.o enclave.o file.o foreshadow.o gdt.o idt.o pt.o sched.o spy.o aep_trampoline.o irq_entry.o rtm.o transient.o libsgx-step.a
[RM] main.o app
[===] Enclave [===]
[GEN] sgx_edger8r encl.edl
[CC]  encl_t.c (trusted edge)
[CC]  encl.c (core)
[LD]   encl.o encl_t.o -lsgx_trts encl.unsigned.so
[SGN] encl.unsigned.so
[CC]  encl_u.c (untrusted edge)
[AR]   libencl_proxy.a
[===] ../../libsgxstep [===]
[CC]  apic.c
[CC]  cpu.c
[CC]  debug.c
[CC]  enclave.c
[CC]  file.c
[CC]  foreshadow.c
[CC]  gdt.c
[CC]  idt.c
[CC]  pt.c
[CC]  sched.c
[CC]  spy.c
[AS]  aep_trampoline.S
[AS]  irq_entry.S
[AS]  rtm.S
[AS]  transient.S
[AR]  libsgx-step.a
[CC]  main.c
[LD] main.o -o app
./app: symbol lookup error: /usr/lib/libsgx_uae_service.so: undefined symbol: _ZN6google8protobuf2io16CodedInputStream20ReadVarint32FallbackEPj
Makefile:48: recipe for target 'run' failed
make: *** [run] Error 127

**Comment by barshuker** [comment]
Solved. i rebuild everything from the start.

**Comment by jovanbulck** [comment]
Great, I'll close this issue. Sorry didn't see you troubles earlier.. These are indeed typical linker dependency problems fixed by setting the environment as described in the linux-sgx README :)

**Comment by ccjingwen** [comment]
I have the same problem. May I ask which part of the environment setting is wrong?

**Comment by ccjingwen** [comment]
> Hey, i'm currently trying to build the 'foreshadow' app but when i run the makefile i get this error:
> 
> [===] Enclave [===]
> [GEN] sgx_edger8r encl.edl
> make[1]: sgx_edger8r: Command not found
> Makefile:84: recipe for target 'edger' failed
> make[1]: *** [edger] Error 127
> Makefile:72: recipe for target 'build-Enclave' failed
> make: *** [build-Enclave] Error 2
> 
> I edited the makefile inside the 'Enclave' folder by:
> 
> * adding the line:
>   SGX_SDK ?= /opt/intel/sgxsdk
>   (when i tried to print the value of SGX_SDK through "echo" i got blank output).
> * changing the EDGER variable to be
>   EDGER		  = $(SGX_SDK)/bin/x64/sgx_edger8r
> 
> the error above seemed to be solved but then i encountered a new one:
> [===] Enclave [===]
> [GEN] /opt/intel/sgxsdk/bin/x64/sgx_edger8r encl.edl
> [CC] encl_t.c (trusted edge)
> [CC] encl.c (core)
> [LD] encl.o encl_t.o -lsgx_trts encl.unsigned.so
> Makefile:51: recipe for target 'encl.so' failed
> make[1]: *** [encl.so] Error 127
> Makefile:72: recipe for target 'build-Enclave' failed
> make: *** [build-Enclave] Error 2
> 
> i followed the installation instructions inside the README, would appreciate some help.
> 
> Thanks,
> Bar.

I have the same problem. May I ask which part of the environment setting is wrong?

**Comment by jovanbulck** [comment]
this is normally not an issue in SGX-Step, but indicates that you didn't set the environment for yr SGX-SDK installation properly. You should normally do `source /opt/intel/sgxsdk/environment` in the shell where you execute the Makefile

Hope this helps

**Comment by ccjingwen** [comment]
Great!Solved,thanks!
