### ISSUE TITLE
Compilation errors in sgx_encl.c and sgx_util.c

### ISSUE THREAD

**Issue by JunyeonL** [jovanbulck/sgx-step#14]
When I try to install SGX_driver, I get the following compilation errors.
This part should be changed to automatically choose whether to use vm_insert_pfn or vmf_insert_pfn, depending on your version of Linux Kernel.

------------------------------------------------------------------------------------------------
error: implicit declaration of function ‘vm_insert_pfn’; did you mean ‘vmf_insert_pfn’? [-Werror=implicit-function-declaration]
  rc = vm_insert_pfn(vma, entry->addr, PFN_DOWN(entry->epc_page->pa));
       ^~~~~~~~~~~~~
       vmf_insert_pfn

error: implicit declaration of function ‘vm_insert_pfn’; did you mean ‘vmf_insert_pfn’? [-Werror=implicit-function-declaration]
  ret = vm_insert_pfn(vma, encl_page->addr, PFN_DOWN(epc_page->pa));
        ^~~~~~~~~~~~~
        vmf_insert_pfn
--------------------------------------------------------------------------------------------------

Starting with Kernel 4.20, vm_insert_pfn transitions to vmf_insert_pfn breaking backward compatibility.

http://web.ist.utl.pt/joao.leao.guerreiro/2019/04/setting-up-a-sgx-development-environment/

Thanks

**Comment by jovanbulck** [comment]
Thanks for reporting. This is an issue in the linux-sgx-driver dependent project and has been fixed in [v2.5](https://github.com/intel/linux-sgx-driver/commit/d617da1c721fb7023889bc791e34f117668464ff#diff-a00075becbea94f898b653443202a9ed)

Hence, Im marking this as a TODO update the patches to upstream linux-sgx v2.5
