### ISSUE TITLE
periodic mode

### ISSUE THREAD

**Issue by shujiecui** [jovanbulck/sgx-step#26]
Hi,
How could sgx-step support APIC periodic mode?

Shujie

**Comment by jovanbulck** [comment]
This is explained in the Intel Software Developer Manual "Table 10-2. Local APIC Timer Modes". Just add the required bitmask here:

https://github.com/jovanbulck/sgx-step/blob/master/libsgxstep/apic.h#L50

The timer configuration code can then be trivially changed here:

https://github.com/jovanbulck/sgx-step/blob/master/libsgxstep/apic.c#L66

**Comment by shujiecui** [comment]
Got it. Thanks
