### ISSUE TITLE
How to execute it

### ISSUE THREAD

**Issue by jahidhasanlinix** [jovanbulck/sgx-step#40]
May I know how can I execute the main code file here? Any help

**Comment by jovanbulck** [comment]
Sorry for a delayed reply, I didn't notice this issue. Please see detailed instructions on building and running test applications in [section 3 in the README](https://github.com/jovanbulck/sgx-step#3-build-and-run-test-applications).

Closing this now. Feel free to open a new issue if you run into a _concrete_ problem, but please include detailed description and reference output.
