### ISSUE TITLE
undefined symbol : sgx_get_aep

### ISSUE THREAD

**Issue by yashwanthresham** [jovanbulck/sgx-step#44]
![Screenshot from 2022-04-18 11-39-19](https://user-images.githubusercontent.com/36885183/164606640-c05ffa64-f179-4592-94a0-22bc56ba1d91.png)
![Screenshot from 2022-04-12 23-58-17](https://user-images.githubusercontent.com/36885183/164606644-cd857f4b-4456-43ac-b1a3-7b7d96f0fe1c.png)
![Screenshot from 2022-04-12 23-58-46](https://user-images.githubusercontent.com/36885183/164606647-2616430b-e67c-4bde-a27c-acebb36870f6.png)
while performing make run in app/aep_redirect it shows sgx_get_aep undefined. 
Tried the solution in issue #24 but error still exits.

**Comment by jovanbulck** [comment]
Hm, there is clearly something wrong with linking to the correct patched URTS SGX library. It seems, however, you are trying several things at once.

Instead of invoking through make run, try directly invoking ./app with LD_LIBRARY_PATH and ldd to figure out which versions you are using. Perhaps try:

```

#43

**Comment by jovanbulck** [comment]
it appears from the screenshots your default urts is under `/lib/x86_64-linux-gnu/`, and as far as I see, you didn't `nm` `grep` this one, so it is probably from another non-patched SDK you installed there(?) In general, it is easiest if you remove/purge any other SDKs so only the patched one is left -- if not, you'll have to manually `LD_LIBRARY_PATH` the correct path (under psw not sdk, otherwise you'll get the first error in your screenshot as discussed in #43)

hope it helps! let me know if/how your figure it out!

**Comment by yashwanthresham** [comment]
![1](https://user-images.githubusercontent.com/36885183/164960687-71b6b7fb-8252-4814-b449-374e7a77e62e.png)
![2](https://user-images.githubusercontent.com/36885183/164960691-c7cfd09f-0aab-48d0-a75f-3152e569f520.png)
![3](https://user-images.githubusercontent.com/36885183/164960692-c719423d-9b9a-493b-aaa4-4872044577fd.png)

I have reinstalled sgxsdk and psw. and tried the above commands. Also when i try to load the /.install_sgx_driver.sh it gives me error .
![4](https://user-images.githubusercontent.com/36885183/164960778-8858cfc8-7227-4afc-b06a-1795dae7077b.png)

**Comment by yashwanthresham** [comment]
i have pulled the recent version of sgxstep and installed the driver downloaded from the https://download.01.org/intel-sgx/sgx-linux/2.16/distro/ubuntu20.04-server/ link. 

When i try to run  ./install_sgx_driver.sh it gives "" modprobe : isgx cannot be performed "" .
![27 april](https://user-images.githubusercontent.com/36885183/165506790-4ee75491-03cf-45d3-b1b7-13499733ddea.png)
![27_ap](https://user-images.githubusercontent.com/36885183/165506824-a66c0b97-0c70-4dea-8781-2c27823fa875.png)

**Comment by jovanbulck** [comment]
It seems like you're using the latest (upstream) Linux kernel driver. This is currently not supported on SGX-Step, see issue #39 

Please make sure to build and use the `linux-sgx-driver` as documented in the README.

Hope it helps!

**Comment by yashwanthresham** [comment]
can you please explain what to be done for latest driver. 
i have dowgrading the linux driver to 5.8.* it also gives error "isgx operation not permitted"

**Comment by jovanbulck** [comment]
I cannot help if you are not more specific, please provide *full* detailed commands and terminal output (to be more readible: best to copy-paste here instead of screenshots)

The process for the SGX driver is detailed here:

**Comment by yashwanthresham** [comment]
yashwanth@yashwanth-ROG-Strix-G531GD-G531GD:~/sgx-step/kernel$ uname -r
5.8.0-63-generic
Above is the linux kernel driver version , not the sgx driver. 

yashwanth@yashwanth-ROG-Strix-G531GD-G531GD:~/sgx-step/kernel$ ./install_SGX_driver.sh 
make -C /lib/modules/5.8.0-63-generic/build M=/home/yashwanth/sgx-step/kernel/linux-sgx-driver modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-63-generic'
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_main.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_page_cache.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_ioctl.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_vma.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_util.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_encl.o
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/sgx_encl2.o
  LD [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/isgx.o
  MODPOST /home/yashwanth/sgx-step/kernel/linux-sgx-driver/Module.symvers
  CC [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/isgx.mod.o
  LD [M]  /home/yashwanth/sgx-step/kernel/linux-sgx-driver/isgx.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-63-generic'
modprobe: ERROR: could not insert 'isgx': Operation not permitted

yashwanth@yashwanth-ROG-Strix-G531GD-G531GD:~/sgx-step/kernel$ make clean load
make -C /lib/modules/5.8.0-63-generic/build M=/home/yashwanth/sgx-step/kernel clean
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-63-generic'
  CLEAN   /home/yashwanth/sgx-step/kernel/Module.symvers
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-63-generic'
sudo rmmod sgx-step.ko || true
rmmod: ERROR: Module sgx_step is not currently loaded
make -C /lib/modules/5.8.0-63-generic/build M=/home/yashwanth/sgx-step/kernel modules
make[1]: Entering directory '/usr/src/linux-headers-5.8.0-63-generic'
  CC [M]  /home/yashwanth/sgx-step/kernel/sgxstep.o
/home/yashwanth/sgx-step/kernel/sgxstep.c: In function ‘sgx_step_ioctl_edbgrd’:
/home/yashwanth/sgx-step/kernel/sgxstep.c:99:5: warning: ISO C90 forbids variable length array ‘buf’ [-Wvla]
   99 |     uint8_t buf[data->len];
      |     ^~~~~~~
/home/yashwanth/sgx-step/kernel/sgxstep.c: In function ‘sgx_step_get_pt_mapping’:
/home/yashwanth/sgx-step/kernel/sgxstep.c:148:14: warning: #warning 5-level page tables currently not supported by SGX-Step [-Wcpp]
  148 |             #warning 5-level page tables currently not supported by SGX-Step
      |              ^~~~~~~
/home/yashwanth/sgx-step/kernel/sgxstep.c:149:14: warning: #warning unfolding dummy p4d; try rebooting with `no5lvl` kernel parameter if needed [-Wcpp]
  149 |             #warning unfolding dummy p4d; try rebooting with `no5lvl` kernel parameter if needed
      |              ^~~~~~~
  LD [M]  /home/yashwanth/sgx-step/kernel/sgx-step.o
  MODPOST /home/yashwanth/sgx-step/kernel/Module.symvers
  CC [M]  /home/yashwanth/sgx-step/kernel/sgx-step.mod.o
  LD [M]  /home/yashwanth/sgx-step/kernel/sgx-step.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.8.0-63-generic'
sudo modprobe -a isgx msr
modprobe: ERROR: could not insert 'isgx': Operation not permitted
make: *** [Makefile:23: load] Error 1

I have installed the linux sgx sdriver from the link provided in the readme of this repo.

**Comment by jovanbulck** [comment]
Okay, the error is clearly the `modprobe` command. Try googling the "Operation not permitted" modrpobe error message.

It seems like you booted your Linux kernel in "secure" mode, which by default doesn't allow to load unsigned kernel drivers.

Try disabling secure boot in UEFI or via these commands (in a root shell): https://unix.stackexchange.com/a/543580
