### ISSUE TITLE
Trying to run app/memcmp but gives assertion error

### ISSUE THREAD

**Issue by kmarzouq** [jovanbulck/sgx-step#62]
I am trying to run app/memcmp and it tells me that the assertion that pwd_len < MAX_LEN is false. I have gotten foreshadow, aep-redirect, and bench to work. I can't figure out whats the issue here. I tested it unmodified and with Debug set to 1. 
![Screenshot from 2023-06-29 11-51-02](https://github.com/jovanbulck/sgx-step/assets/69616884/dc262967-ebe3-4832-a03c-4d4d8c31e9fa)

**Comment by jovanbulck** [comment]
this means the "recovering password length" step failed. Most likely because the single-stepping interval is not set correctly(?)

Try running it as `./app`  (as in the GIF screencast) instead of `make run` so you have interactive output and see more where it goes wrong. If it works for app/bench, then try to slightly decrease the single-step interval if needed.

**Comment by kmarzouq** [comment]
Ok, did `sudo ./app` instead and it got somewhere. I have decreased `SGX_STEP_TIMER_INTERVAL` from the default 53 to various values down to 1 and I get the same result. I make sure to use `make` before running each time after I change `SGX_STEP_TIMER_INTERVAL`. Not sure what the issue is.
![Screenshot from 2023-07-05 11-51-50](https://github.com/jovanbulck/sgx-step/assets/69616884/333c52a9-62ed-438d-91df-761686228d2b)

**Comment by jovanbulck** [comment]
okay, now you clearly got stuck in "zero-stepping", ie the timer interval is too low and the interrupt arrives before ERESUME has completed, meaning the enclave will not execute an instruction and make progress.

Setting the timer interval to values as low as 1 is always going to be too low and not work. Try to first get a better understanding of the correct timer interval and how to assess it ("Note (calibration)" in the top-level README should hopefully help you). Make sure it works reliably with `app/bench` for a large NOP slide and then it should work with the same value for `app/memcmp` too.

**Comment by kmarzouq** [comment]
I think I found the correct Step Interval of 124 but memcmp isn't working.
![Screenshot from 2023-07-12 16-34-57](https://github.com/jovanbulck/sgx-step/assets/69616884/56b08010-27eb-41b0-8814-c09b71aa597c)

**Comment by jovanbulck** [comment]
Hmm too bad. If it works reliably in app/bench then it should normally also work for app/memcp. I'd advise that you try to understand what exactly goes wrong by settign DEBUG=1 in main.c (and maybe LIBSGXSTEP_DEBUG=0 in config.h for readibility). Then you should be able to see if the stepping is going correct, compared to the objdump, and where's the problem exactly.
