### ISSUE TITLE
[load_qe ../qe_logic.cpp:697] Error, call sgx_create_enclave QE fail [load_  Failed to load QE3: 0x4004

### ISSUE THREAD

**Issue by castiel97** [jovanbulck/sgx-step#71]
My ubuntu version is 18.04.1 and kernel version is 5.4.0-150-generic. CPU is intel i7-9700.
I have already set the kernel parameters and all checks in check_sys.sh passed:
.. Checking recommended SGX-Step parameters          [OK]
.. Checking unknown kernel parameters                [OK]
.. Checking CPU features                             [OK]
.. Checking kernel page-table isolation              [OK] 

In step 1 build and load /dev/sgx-step, evething goes well:
![image](https://github.com/jovanbulck/sgx-step/assets/57380117/d55bf610-8b4f-4fa4-aff5-673236db6ebd)

In step 2 patch and install SGX SDK, it seems I have installed sgx sdk successfully:
![image](https://github.com/jovanbulck/sgx-step/assets/57380117/29880995-e4f0-4977-b78c-c705dcb9bdd4)

But when I run this command "sudo service aesmd status", I got an error message:   
![image](https://github.com/jovanbulck/sgx-step/assets/57380117/d49dbf93-e386-4aa2-8f1e-a7798470a461)
I googled this error message and one [solution](https://community.intel.com/t5/Intel-Software-Guard-Extensions/Failed-to-load-QE3-0x4004/m-p/1273696) is to update the bios. But it does not work for my situation.

**Comment by jovanbulck** [comment]
Hi castiel97,

Sorry for a delayed response. Not sure if you figured this out yet? In any case, this is not an SGX-Step issue (the driver and patched SDK  indeed succeeded as you showed above) but an issue with using SGX on your machine in general.

Not sure what's exactly going wrong, but it seems to be an issue with loading the Quoting Enclave (QE). Perhaps it works to load an enclave (if you don't need attestation). I'd recommend to first try and run a simple enclave without sgx-step (eg the SampleEnclave directory of the Intel sdk).

I'm closing this as it doesn't appear to be an SGX-Step issue, but feel free to follow-up.
