### ISSUE TITLE
memcmp example fails to find the secret

### ISSUE THREAD

**Issue by w-woloszyn** [jovanbulck/sgx-step#79]
Hi!

I finally have an opportunity to learn more about this exciting project :)

I have trouble reproducing the memcmp example. I have an out-of-tree driver, done `make clean load ` in the kernel folder, and sys_check goes through. The behaviour is that the guessed password and its length is non-deterministic for me.

Ubuntu and kernel version:
```
wojciech@ww:~/Repos/sgx-step/app/memcmp$ uname -a
Linux ww 6.5.0-25-generic #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2
 x86_64 x86_64 x86_64 GNU/Linux
```

Behavior:
![output](https://github.com/jovanbulck/sgx-step/assets/18660687/9b116ada-3ab1-4971-91b9-de01aaba5d6b)

Any suggestions on what might be wrong are highly appreciated!

Kind regards,
Wojciech

**Comment by jovanbulck** [comment]
Hi @w-woloszyn 

Thanks for your interest in the project and thanks for the PR! Apologies for a delayed response, I was busy with other things..

Glad to hear you figured it out! Improving overall stability and automated timer interval calibration is on my long todo list, which I unfortunately didn't find time for yet.

FIWIW: A reboot is definitely needed for the kernel params to take effect and generally it helps to not have too many other tasks running so the kernel doesn't interfere (normally `isolcpus` should also help for that as per the recommended kernel params).
