### ISSUE TITLE
libsgxstep: default to position-independent code

### ISSUE THREAD

**Issue by shpark** [jovanbulck/sgx-step#8]
Hello
 
I was trying to reproduce the project, however, I failed to build the project

I am using Ubuntu 18.04 and gcc7.3.0

This is the error message I got
```
foreshadow $ make
[===] Enclave [===]
[GEN] sgx_edger8r encl.edl
[CC]  encl_t.c (trusted edge)
[CC]  encl.c (core)
[LD]   encl.o encl_t.o -lsgx_trts encl.unsigned.so
[SGN] encl.unsigned.so
[CC]  encl_u.c (untrusted edge)
[AR]   libencl_proxy.a
[===] ../../libsgxstep [===]
[CC]  apic.c
[CC]  cpu.c
[CC]  debug.c
[CC]  enclave.c
[CC]  file.c
[CC]  foreshadow.c
[CC]  gdt.c
[CC]  idt.c
[CC]  pt.c
[CC]  sched.c
[CC]  spy.c
[AS]  aep_trampoline.S
[AS]  irq_entry.S
[AS]  rtm.S
[AS]  transient.S
[AR]  libsgx-step.a
[CC]  main.c
[LD] main.o -o app
/usr/bin/ld: ../../libsgxstep/libsgx-step.a(aep_trampoline.o): relocation R_X86_64_32S against symbol `sgx_step_tcs' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'app' failed
make: *** [app] Error 1
```

Have you experienced similar issues before?

Thanks!

**Comment by dn0sar** [comment]
Try with an older version of gcc (e.g. 4.8 with -std=gnu99), I ran into the same problem and that solved it

**Comment by shpark** [comment]
@dn0sar Thank you for your help! It seems to work. It wouldn't be easy to pinpoint the bug without your help. And now I close the issue

**Comment by giusef** [comment]
Hi all, I also can confirm this on Ubuntu 18.04 LTS with gcc-7 and gcc-8. Maybe I should try to install a clean Ubuntu 16.04 with gcc-4.8 but I would ask you if there is any fix before. Thanks in advance.

**Comment by jovanbulck** [comment]
so I somehow missed this issue since it was closed... Seems that more recent GCC versions switched to position independent code by default, whereas some of the hand-written asm code in libsgxstep is still using position-dependent code. I'll re-open this issue and fix this in a future commit ^^
