### ISSUE TITLE
SIGSEGV right after launch

### ISSUE THREAD

**Issue by zyongye** [jovanbulck/sgx-step#81]
Hello, 
     I followed all the steps on README and installed sgx-step. But it gives me immediate fault after running the program. 
The command I run
```
cd app/bench
make run
```
![Screenshot 2024-04-11 at 9 04 22 PM](https://github.com/jovanbulck/sgx-step/assets/42426329/786cabfc-7f7e-4137-b68b-bea8157745f2)

I am running with Kernel both 5.19 and 6.5 it gives me the same error. Here is my boot parameter
![Screenshot 2024-04-11 at 9 05 09 PM](https://github.com/jovanbulck/sgx-step/assets/42426329/4d5c19f7-cb22-4fb7-a430-8bba5c60f405)

Not sure where goes wrong. 

Thanks in advance!!

**Comment by zyongye** [comment]
Re-read the code and find out that's the feature ;)

**Comment by jovanbulck** [comment]
glad you figured it out! Yes, the page fault is used to track enclaved execution to a specific starting point to then enable single-stepping :)
